### ISSUE TITLE
[AspireE2E]After installing aspire extension in vs code, aspire run the project, in dashboard, select console> select apiservice > click "stop resource" button. dotnet watch information show up

### ISSUE THREAD

**Issue by Susie-1989** [microsoft/aspire#13685]
REGRESSION INFO: Works well aspire 13.1.0

**INSTALL STEPS**

1.OS: Windowsx64
2.Install VS Code insider - 1.108.0
4.Install SDK 10.0.101
5.isntall aspire extension -1.0.2
6. Install aspire cli -version: 13.2.0-preview.1.25621.1
`iex "& { $(irm https://aspire.dev/install.ps1) } -Quality dev"`

**REPRO STEPS**

1. Open vs code > Ctrl + Shift + P >search "aspire" > aspire: New Aspire project > Start App(ASP.NET/Blazor).
2. Ctrl + Shift + P > Aspire: Open Aspire terminal > type "aspire run"
3. In dashboard, select console> select apiservice > click "stop resource" button.

**ACTUAL**  dotnet watch information show up

<img width="1576" height="555" alt="Image" src="https://github.com/user-attachments/assets/f899f06e-7df1-4141-ab8e-8f96b2d505e9" />

**EXPECTED** No dotnet watch information

<img width="777" height="556" alt="Image" src="https://github.com/user-attachments/assets/e9bf1c8d-e5b4-4266-9563-7fea80678307" />

**Comment by adamint** [comment]
@afscrome the right label is `area-extension`, I'm not sure how vs-code was created. Just saw there's this large backlog of issues

**Comment by adamint** [comment]
I don't know how but this has been fixed.

**Comment by Susie-1989** [comment]
@adamint , This issue still reproduces in 13.3.0-preview.1.26156.8, could you help take a look? thanks.

<img width="772" height="322" alt="Image" src="https://github.com/user-attachments/assets/0207bc11-7123-417d-9c8c-1d1cd918ee18" />

**Comment by adamint** [comment]
> [@adamint](https://github.com/adamint) , This issue still reproduces in 13.3.0-preview.1.26156.8, could you help take a look? thanks.
> 
> <img alt="Image" width="772" height="322" src="https://private-user-images.githubusercontent.com/41678874/561315955-0207bc11-7123-417d-9c8c-1d1cd918ee18.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzMxOTkxNDYsIm5iZiI6MTc3MzE5ODg0NiwicGF0aCI6Ii80MTY3ODg3NC81NjEzMTU5NTUtMDIwN2JjMTEtNzEyMy00MTdkLTljOGMtMWQxY2Q5MThlZTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzExVDAzMTQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwM2ZiNTdkMTVhNDQ2NzZiZGVhMjhhZDBiZDE2YmE4NTkwMWJiNDUxNzk5ZDFmOGU4ZDAyNjBhZjdhMmUzY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jvVCvxH4ICoGbnv50dn6NSZZD6T3chyt79ACjmFaKsU">

@Susie-1989 are you also using a daily version of the aspire extension?

**Comment by Susie-1989** [comment]
Hi @adamint  when use a daily version of the aspire extension(version: 1.0.4, install link: iex "& { $(irm https://aspire.dev/install.ps1) } -InstallExtension -Quality dev -UseInsiders"), this issue still reproduces.

**Comment by adamint** [comment]
Interesting, I'll reopen. As the stop succeeds, setting priority to low

**Comment by adamint** [comment]
Closing as wontfix
